CREATE TABLE IF NOT EXISTS DOCTOR (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PATIENT (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    DOCTOR_ID INT(11) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    STATUS TINYINT NOT NULL,
    WEIGHT FLOAT NOT NULL,
    HEIGHT FLOAT NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    TEST_DATE DATE NULL,
    FOREIGN KEY DOCTOR_FK (DOCTOR_ID) REFERENCES DOCTOR(ID),
    INDEX DOCTOR_IDX (DOCTOR_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MEDICATION (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(500)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PATIENT_MEDICATION (
    PATIENT_ID INT(11) NOT NULL,
    MEDICATION_ID INT(11) NOT NULL,
    FOREIGN KEY PATIENT_FK (PATIENT_ID) REFERENCES PATIENT (ID) ON DELETE CASCADE,
    FOREIGN KEY MEDICATION_FK (MEDICATION_ID) REFERENCES MEDICATION (ID) ON DELETE CASCADE
) ENGINE=INNODB;
